dist: bionic
language: python
addons:
  apt:
    packages:
      - libjpeg-turbo8-dev
      - libturbojpeg0-dev

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
install: pip install tox-travis
script: tox
